### ISSUE TITLE
Rails 3 compatible?

### ISSUE THREAD

**Issue by rurounijones** [mislav/standardista#2]
I just installed the standardista plugin to a rails 3 app and there are certain tags generated from within rails that are not being converted (such as meta and text_field form tags).

I seem to remember these working in Rails 2.

Is standardista Rails 3 compatible? (If not, Is it planned to be or is there a new preferred way to get HTML4 output)

**Comment by mislav** [comment]
I haven't used Standardista in Rails 3 apps. I encourage you to try and modify it to handle Rails 3 helpers as well. While doing so, try to keep compatibility with older Rails, too.

**Comment by rurounijones** [comment]
When I looked into it there is nothing standardista can really do. 

The self-closing nature of the tags in question is hard-coded in an i string literal (Thank you Rails team) so I ended up just monkey-patching those two methods, deleting a character and all is good.

Not the best I know, but was simple and worked for me.

Thinking about it you could probably alias the method and gsub out the closing / but what the hey.
